-
  name: Linux targets
  gather_facts: no
  hosts: linux
  roles:
    - linux

-
  name: macOS targets
  gather_facts: no
  hosts: macos
  roles:
    - macos

-
  name: Windows targets
  gather_facts: no
  hosts: windows
  roles:
    - windows