site_name: 'RustHunter'
site_url: https://rusthunter.readthedocs.io/
docs_dir: docs

nav:
  - 'Introduction':
    - 'What is RustHunter?' : 'index.md'
    - 'Architecture': 'introduction/architecture.md'
  - 'Quickstart':
    - 'Windows': 'quickstart/windows.md'
    - 'Linux': 'quickstart/linux.md'
  - 'Plugins':
    - 'Windows':
      - 'windows_users': 'plugins/windows-plugins/windows_users.md'
      - 'windows_administrators': 'plugins/windows-plugins/windows_administrators.md'
      - 'windows_tcp_listen': 'plugins/windows-plugins/windows_tcp_listen.md'
      - 'windows_udp_listen': 'plugins/windows-plugins/windows_udp_listen.md'
      - 'windows_autoruns': 'plugins/windows-plugins/windows_autoruns.md'
      - 'windows_yara': 'plugins/windows-plugins/windows_yara.md'
    - 'Linux':
      - 'linux_users': 'plugins/linux-plugins/linux_users.md'
      - 'linux_root': 'plugins/linux-plugins/linux_root.md'
      - 'linux_tcp_listen': 'plugins/linux-plugins/linux_tcp_listen.md'
      - 'how_many_cronjobs': 'plugins/linux-plugins/how_many_cronjobs.md'
      - 'linux_dns_in_use': 'plugins/linux-plugins/linux_dns_in_use.md'
      - 'linux_unusual_network_usage': 'plugins/linux-plugins/linux_unusual_network_usage.md'
      - 'linux_unusual_suid_root_files': 'plugins/linux-plugins/linux_unusual_suid_root_files.md'
      - 'linux_uptime': 'plugins/linux-plugins/linux_uptime.md'
    - 'macOS':
      - 'macos_users': 'plugins/macos-plugins/macos_users.md'
  - 'Development':
    - 'Basic Linux plugin': 'development/basic_linux_plugin.md'
  - 'References':
    - 'Contributing': 'references/contributing.md'
    - 'Credits': 'references/credits.md'

theme: 
  name: 'material'
  logo: 'images/logo_small.png'
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences