site_name: 'RustHunter'
site_url: https://rusthunter.readthedocs.io/
docs_dir: docs

nav:
  - 'Introduction':
    - 'What is RustHunter?' : 'index.md'
    - 'Architecture': 'introduction/architecture.md'
  - 'Linux':
    - 'Setup': 'linux/setup.md'
    - 'Configuration': 'linux/configuration.md'
    - 'Local snapshot': 'linux/local.md'
    - 'Global snapshot': 'linux/global.md'
    - 'Compare': 'linux/compare.md'
    - 'Encryption': 'linux/encryption.md'
  - 'Windows':
    - 'Setup': 'windows/setup.md'
    - 'Local snapshot': 'windows/local.md'
    - 'Global snapshot': 'windows/global.md'
    - 'Compare': 'windows/compare.md'
    - 'Encryption': 'windows/encryption.md'
  - 'Plugins':
    - 'Windows':
      - 'windows_users': 'plugins/windows-plugins/users.md'
      - 'windows_administrators': 'plugins/windows-plugins/administrators.md'
      - 'windows_tcp_listen': 'plugins/windows-plugins/tcp_listen.md'
      - 'windows_udp_listen': 'plugins/windows-plugins/udp_listen.md'
      - 'windows_autoruns': 'plugins/windows-plugins/autoruns.md'
      - 'windows_yara': 'plugins/windows-plugins/yara.md'
    - 'Linux':
      - 'linux_crontab': 'plugins/linux-plugins/crontab.md'
      - 'linux_dns': 'plugins/linux-plugins/dns.md'
      - 'linux_guid': 'plugins/linux-plugins/guid.md'
      - 'linux_promisc': 'plugins/linux-plugins/promisc.md'
      - 'linux_root': 'plugins/linux-plugins/root.md'
      - 'linux_suid': 'plugins/linux-plugins/suid.md'
      - 'linux_tcp_listen': 'plugins/linux-plugins/tcp_listen.md'
      - 'linux_users': 'plugins/linux-plugins/users.md'
    - 'macOS':
      - 'macos_users': 'plugins/macos-plugins/users.md'
  - 'Development':
    - 'Basic Linux plugin': 'development/basic_linux_plugin.md'
  - 'References':
    - 'Contributing': 'references/contributing.md'
    - 'Credits': 'references/credits.md'

theme: 
  name: 'material'
  logo: 'images/logo_small.png'
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences