site_name: 'RustHunter'
site_url: https://rusthunter.readthedocs.io/
docs_dir: docs

nav:
  - 'Introduction':
    - 'What is RustHunter?' : 'index.md'
    - 'Architecture': 'introduction/architecture.md'
  - 'Tutorial':
    - 'Linux':
      - 'Setup': 'tutorial/linux/setup.md'
      - 'Configuration': 'tutorial/linux/configuration.md'
      - 'Local snapshot': 'tutorial/linux/local.md'
      - 'Global snapshot': 'tutorial/linux/global.md'
      - 'Compare': 'tutorial/linux/compare.md'
      - 'Encryption': 'tutorial/linux/encryption.md'
      - 'Update': 'tutorial/linux/update.md'
    - 'Windows':
      - 'Setup': 'tutorial/windows/setup.md'
      - 'Local snapshot': 'tutorial/windows/local.md'
      - 'Global snapshot': 'tutorial/windows/global.md'
      - 'Compare': 'tutorial/windows/compare.md'
      - 'Encryption': 'tutorial/windows/encryption.md'
      - 'Update': 'tutorial/windows/update.md'
  - 'Plugins':
    - 'All': 'plugins/all.md'
    - 'Linux':
      - 'crontab': 'plugins/all/linux-plugins/crontab.md'
      - 'dns': 'plugins/all/linux-plugins/dns.md'
      - 'guid': 'plugins/all/linux-plugins/guid.md'
      - 'promisc': 'plugins/all/linux-plugins/promisc.md'
      - 'root': 'plugins/all/linux-plugins/root.md'
      - 'suid': 'plugins/all/linux-plugins/suid.md'
      - 'tcp_listen': 'plugins/all/linux-plugins/tcp_listen.md'
      - 'users': 'plugins/all/linux-plugins/users.md'
    - 'Windows':
      - 'users': 'plugins/all/windows-plugins/users.md'
      - 'administrators': 'plugins/all/windows-plugins/administrators.md'
      - 'tcp_listen': 'plugins/all/windows-plugins/tcp_listen.md'
      - 'udp_listen': 'plugins/all/windows-plugins/udp_listen.md'
      - 'autoruns': 'plugins/all/windows-plugins/autoruns.md'
      - 'yara': 'plugins/all/windows-plugins/yara.md'
      - 'domain_users': 'plugins/all/windows-plugins/domain_users.md'
      - 'domain_computers': 'plugins/all/windows-plugins/domain_computers.md'
      - 'domain_group': 'plugins/all/windows-plugins/domain_group.md'
    - 'macOS':
      - 'users': 'plugins/all/macos-plugins/users.md'
  - 'Development':
    - 'Basic Linux plugin': 'development/basic_linux_plugin.md'
    - 'Linux plugin with external script': 'development/linux_plugin_script.md'
    - 'Basic Windows plugin': 'development/basic_windows_plugin.md'
    - 'Windows plugin with parameters': 'development/windows_plugin_parameters.md'
  - 'References':
    - 'Contributing': 'references/contributing.md'
    - 'Credits': 'references/credits.md'

theme: 
  name: 'material'
  logo: 'images/logo_small.png'
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences