- name: Creating remote path
  win_file:
    path: "{{ remote_path }}"
    state: directory

- name: Uploading files
  win_copy:
    src: "{{ item }}"
    dest: "{{ remote_path }}"
  with_fileglob: "files/*"

- name: Collecting data
  win_command: "{{ remote_path }}{{ rusthunter_executable }} {{ rusthunter_run_subcommand }} --tag {{ snapshot_tag }}"
  register: shell_result
  args:
    chdir: "{{ remote_path }}"

- name: Data output
  when: debug
  debug:
    var: shell_result.stdout_lines

- name:  Finding snapshosts 
  find:
    paths: "{{ remote_path }}"
    patterns: "{{ snapshot_tag }}_*.{{ snapshot_extension }}"
  register: snapshots_to_fetch

- name: Snapshot listing
  when: debug
  debug:
    var: snapshots_to_fetch

- name: Retrieving data
  fetch:
    src: "{{ item.path }}"
    dest: "{{ snapshots_path }}"
    flat: yes
  with_items: "{{ snapshots_to_fetch.files }}"

- name: Removing remote path
  win_file:
    path: "{{ remote_path }}"
    state: absent
