- name: Clean-up
  win_file:
    path: "{{ remote_path }}"
    state: absent

- name: Remote path creation
  win_file:
    path: "{{ remote_path }}"
    state: directory

- name: Files upload
  win_copy:
    src: "{{ item }}"
    dest: "{{ remote_path }}"
  with_fileglob: "files/*"

- name: Snapshotting
  win_command: "{{ remote_path }}{{ rusthunter_executable }} {{ rusthunter_run_subcommand }} --tag {{ snapshot_tag }}"
  register: shell_result
  args:
    chdir: "{{ remote_path }}"

- name: Snapshot output [DEBUG]
  when: debug
  debug:
    var: shell_result.stdout_lines

- name: Snapshot file finding 
  win_find:
    paths: "{{ remote_path }}"
    patterns: "{{ snapshot_tag }}_*.{{ snapshot_extension }}"
  register: snapshots_to_fetch

- name: Snapshot file listing [DEBUG]
  when: debug
  debug:
    var: snapshots_to_fetch

- name: Snapshot download
  fetch:
    src: "{{ item.path }}"
    dest: "{{ snapshots_path }}"
    flat: yes
  with_items: "{{ snapshots_to_fetch.files }}"

- name: Clean-up
  win_file:
    path: "{{ remote_path }}"
    state: absent