- name: Clean-up
  file:
    path: "{{ remote_path }}"
    state: absent
    
- name: Remote path creation
  file:
    path: "{{ remote_path }}"
    state: directory
    mode: '0777'

- name: Files upload
  copy:
    src: "{{ item }}"
    dest: "{{ remote_path }}"
  with_fileglob: "files/*"

- name: Execution permission setting
  file:
    path: "{{ remote_path }}"
    mode: u=rwx,g=rwx,o=rwx
    recurse: yes

- name: Snapshotting
  command: "{{ remote_path }}{{ rusthunter_executable }} {{ rusthunter_run_subcommand }} --tag {{ snapshot_tag }}"
  become: yes
  become_method: sudo
  register: shell_result
  args:
    chdir: "{{ remote_path }}"

- name: Snapshot output [DEBUG]
  when: debug
  debug:
    var: shell_result.stdout_lines

- name: Snapshot file finding
  find:
    paths: "{{ remote_path }}"
    patterns: "{{ snapshot_tag }}_*.{{ snapshot_extension }}"
  register: snapshots_to_fetch

- name: Snapshot listing [DEBUG]
  when: debug
  debug:
    var: snapshots_to_fetch

- name: Snapshot download
  fetch:
    src: "{{ item.path }}"
    dest: "{{ snapshots_path }}"
    flat: yes
  with_items: "{{ snapshots_to_fetch.files }}"

- name: Clean-up
  file:
    path: "{{ remote_path }}"
    state: absent