name: Docs

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install MkDocs
      run: sudo pip install -r docs/requirements.txt
      
    - name: Build
      run: mkdocs build