name: Linux

on:
  push:
    branches:
      - ['main', 'dev']
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: ${{github.workspace}}/app
      run: cargo build --verbose

    - name: Test
      working-directory: ${{github.workspace}}/app
      run: cargo test --verbose

