name: MacOS

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Remove build config
      working-directory: ${{github.workspace}}/app
      run: rm -rf .cargo

    - name: Build
      working-directory: ${{github.workspace}}/app
      run: cargo build --verbose

    - name: Test
      working-directory: ${{github.workspace}}/app
      run: cargo test --verbose

