name: Validation

on:
  push:
    branches:
      - main
      - dev 
         
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Execution permissions
      run: chmod +x ./rusthunter.sh

    - name: Installation
      run: sudo ./rusthunter.sh install

    - name: Validation Tests
      run: sudo ./rusthunter.sh test --validation