name: Validation

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Execution permissions
      run: chmod +x ./rusthunter.sh
      
    - name: Validation tests
      run: sudo ./rusthunter.sh test --validation