name: Windows

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validation Tests
      shell: pwsh
      run: .\rusthunter.ps1 test -ValidationTests
