name: Windows

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Switch to Linux container mode
      shell: pwsh
      run: |
        Start-Process $Env:ProgramFiles\Docker\Docker\DockerCli.exe -ArgumentList "-SwitchLinuxEngine"

    - name: Validation Tests
      shell: pwsh
      run: |
        powershell -ep bypass .\rusthunter.ps1 install

    - name: Validation Tests
      shell: pwsh
      run: |
        powershell -ep bypass .\rusthunter.ps1 test -ValidationTests

    - name: Validation Tests
      shell: pwsh
      run: |
        powershell -ep bypass .\rusthunter.ps1 uninstall
