name: Windows

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: ${{github.workspace}}\app
      run: cargo build --verbose

    - name: Test
      working-directory: ${{github.workspace}}\app
      run: cargo test --verbose

